# K-Fold Cross Validation

It is used to estimate the skill of the machine learning algorithm when it is used to make predictions on data not used to train the model, by spliting the data into k parts and using k-1 parts to train the model and the remaining part to test the model. The model is trained on the k-1 parts and tested on the remaining part.

In [7]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



In [8]:
# load data

digits = load_digits()
X = digits.data
y = digits.target

In [9]:
# train & test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
# Svm
svm = SVC(kernel='linear')
# Fit the model
svm.fit(X_train, y_train)
# predict the model
y_pred = svm.predict(X_test)
# accuracy score
accuracy_score(y_test, y_pred)
# score 
svm.score(X_test, y_test)



0.9777777777777777

In [20]:
# logistic regression
lr = LogisticRegression()
lr.fit(X_train, y_train)

# score
score = lr.score(X_test, y_test)
print("Score:", score)

Score: 0.9694444444444444


c:\Users\ahmed\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
# random forest
rm = RandomForestClassifier(n_estimators=40)
rm.fit(X_train, y_train)

# predict the model
y_pred = rm.predict(X_test)
# accuracy score
accuracy_score(y_test, y_pred)
# score 
rm.score(X_test, y_test)

0.9694444444444444

In [17]:
# cross val score function
from sklearn.model_selection import cross_val_score

In [23]:
# logistic regression perfromance using cross val score
cross_val_score(lr, X, y, cv=5)

c:\Users\ahmed\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ahmed\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [24]:
# svm perfromance using cross val score
cross_val_score(svm, X, y, cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [26]:
# random forest perfromance using cross val score
cross_val_score(RandomForestClassifier(n_estimators=40), X, y, cv=5)

array([0.93055556, 0.89722222, 0.94986072, 0.96657382, 0.9275766 ])

In [36]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold

# parameter tunning using k fold cross validation
score1 = cross_val_score(RandomForestClassifier(n_estimators=5), X, y, cv=3)

np.average(score1)

np.float64(0.8414023372287144)

In [37]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=10), X, y, cv=5)

np.average(score2)

np.float64(0.9032141751779635)

In [38]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=15), X, y, cv=10)

np.average(score3)

np.float64(0.9365797641216634)

In [ ]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=20), X, y, cv=15)

np.average(score4)

np.float64(0.9471101774042949)

In [41]:
score5 = cross_val_score(RandomForestClassifier(n_estimators=30), X, y, cv=20)

np.average(score5)

np.float64(0.9599126092384518)

In [46]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



In [47]:
# load the datset 
data = load_iris()
X = data.data
y = data.target

In [48]:
# splitting dataset into train and test

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
# SVM
svm = SVC(kernel='linear')
svm.fit(x_train, y_train)

# score
svm.score(x_test, y_test)

1.0

In [50]:
# Random Forest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)

# score
rf.score(x_test, y_test)

1.0

In [52]:
# Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)

# score
lr.score(X_test, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [1437, 120]